variables:
  LATEX_IMAGE: texlive/texlive:latest

# Debian packages required:
#   curl
#   inkscape
#   texlive-fonts-extra
#   texlive-lang-german
#   texlive-latex-base
#   texlive-latex-extra
#   texlive-latex-recommended
#   texlive-plain-generic

# Default job
build:
  image: $LATEX_IMAGE
  stage: build
  only:
    - master
    - tags
  except:
    - develop
  tags:
    - asprunner
  artifacts:
    paths:
      - fraunhofer.tds.zip
      - fraunhofer.pdf
      - fraunhofer-article.tex
      - fraunhofer-article.pdf
      - fraunhofer-beamer.tex
      - fraunhofer-beamer.pdf
      - fraunhofer-book.tex
      - fraunhofer-book.pdf
      - fraunhofer-letter.tex
      - fraunhofer-letter.pdf
      - fraunhofer-poster.tex
      - fraunhofer-poster.pdf
      - fraunhofer-report.tex
      - fraunhofer-report.pdf
  before_script:
    - apt-get update
    - apt-get install -y inkscape curl texlive-fonts-extra texlive-lang-german texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-plain-generic
    - 'curl --location --output frutiger.tds.zip --header "PRIVATE-TOKEN: $FRUTIGER_READ_API_TOKEN" "https://gitlab.cc-asp.fraunhofer.de/api/v4/projects/$FRUTIGER_PROJECT_ID/jobs/artifacts/master/raw/frutiger.tds.zip?job=build"'
    - unzip -o frutiger.tds.zip -d $(kpsewhich --var-value TEXMFLOCAL)
    - mktexlsr
    - updmap --sys --enable Map=frutiger.map
  script:
    - make
    - make install
    - make test
