[display]
collapse_preview = false
scroll_offset    = 8
show_icons       = true
column_ratio     = [ 1, 4, 3 ]

    [display.sort]
    method            = "mtime"
    directories_first = false

[preview]
max_preview_size            = 999999999
# max_preview_size = 2097152                           # 2MB
preview_script = "~/.config/joshuto/preview_file.sh" # make sure it's marked as executable
# max_preview_size = 50000097152
# preview_script = "~/.config/joshuto/preview_file.sh"
preview_shown_hook_script = "~/.config/joshuto/uberzug/on_preview_shown.sh"
preview_removed_hook_script = "~/.config/joshuto/uberzug/on_preview_removed.sh"

# [tab]
# inherit, home, root
# home_page = "home"
