#!/bin/bash

# File              : check_powerbutton
# Author            : Bernd Müller <bernd@muellerbernd.de>
# Date              : 14.07.2023
# Last Modified Date: 14.07.2023
# Last Modified By  : Bernd Müller <bernd@muellerbernd.de>

while true; do
# while pgrep i3lock &> /dev/null; do
  read -s -n1 key
  echo "$key"
  case $key in
    $'\e') sh ./toggleLaptopKeyboard.sh && break;;
    'q') sh ./toggleLaptopKeyboard.sh && break;;
  esac
  sleep 1
done
# vim: set ts=2 sw=2:
