-- -- require("bemu.plugins.fidget")
-- require 'bemu.plugins.nvim-treesitter'
-- require 'bemu.plugins.completion'
--
-- require 'bemu.plugins.asynctasks'
-- require 'bemu.plugins.neoformat'
-- require 'bemu.plugins.comment'
-- require 'bemu.plugins.gitsigns'
-- require 'bemu.plugins.vimheader'
-- require 'bemu.plugins.autopairs'
--
-- require 'bemu.plugins.dap'
--
-- require 'bemu.plugins.mk-preview'
--
