#!/usr/bin/env bash


# wallpaper="$(fd . ~/Pictures/wallpapers -t f | shuf -n 1)"

cleaner=("lxpolkit" "dunst" "wl-paste" "nm-applet" "waybar" "blueman" "nextcloud" "hyprpaper" "hypridle" "shikane" "eww" "yambar" "mako" "nextcloud")

for str in "${cleaner[@]}"
do
    kill -SIGTERM $(pgrep -f "$str")
done

mako &
lxpolkit &
foot --server &
wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &
wl-paste --primary --watch cliphist store &
nm-applet &
blueman-applet &
nextcloud &
xhost + local: &
gnome-keyring-daemon --start --components=ssh,secrets,pkcs11 &
waybar --config ~/.config/waybar/config-river.jsonc --style ~/.config/waybar/style-river.css &
shikane &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

foot --server &

hypridle &
hyprpaper &

"$HOME"/scripts/check-dotfiles.sh &
