#!/usr/bin/env bash



cleaner=("lxpolkit" "dunst" "wl-paste" "nm-applet" "waybar" "blueman" "nextcloud" "hyprpaper" "hypridle" "shikane" "eww" "yambar" "mako" "nextcloud" "swayidle" "swaybg" "sway-audio-idle-inhibit")

for str in "${cleaner[@]}"
do
    kill -SIGTERM $(pgrep -f "$str")
done

mako &
lxpolkit &
foot --server &
wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &
wl-paste --primary --watch cliphist store &
nm-applet &
blueman-applet &
nextcloud &
# xhost + local: &
gnome-keyring-daemon --start --components=ssh,secrets,pkcs11 &
waybar --config ~/.config/waybar/config-river.jsonc --style ~/.config/waybar/style-river.css &
shikane &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

# hypridle &
# hyprpaper &
# wallpaper="$(fd . ~/Pictures/wallpapers -t f | shuf -n 1)"
swaybg --image "$HOME/wallpapers/black-hole.png" --mode fill &

# sway-audio-idle-inhibit &
swayidle -w \
    timeout 1200 'notify-send -u critical -t 9000 "Locking Screen in 10 seconds"' \
    timeout 1210 "$HOME/scripts/lock_sway.sh" idlehint 1210 \
    timeout 1500 "wlopm --off '*'" resume "wlopm --on '*'" &

"$HOME"/scripts/check-dotfiles.sh &

# # The user dinit instance is shared across all login sessions and all ttys
# # Therefore, only tell it about the first wayland session
# if [ "$WAYLAND_DISPLAY" = "wayland-1" ]; then
#     dinitctl setenv WAYLAND_DISPLAY
#     dinitctl setenv DISPLAY
#     dinitctl restart dbus --force
# fi
